---
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: reboot
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: ubuntu:bionic

install:
  - pip install testinfra molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME foger.$ROLE_NAME
  - cd foger.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
