---
# tasks file for reboot

- include_tasks: freebsd_python.yml
  when: is_freebsd

- name: Gather facts
  setup:

- include_tasks: "{{ ansible_os_family }}.yml"


- name: Install requirements
  package: name="{{ reboot_requirements }}" state=present
  register: install_requirements_result
  until: install_requirements_result is succeeded
  retries: 3
  tags: install


- name: flush handlers
  meta: flush_handlers


- name: Reboot the machine
  reboot:
    pre_reboot_delay: "{{ reboot_delay }}"
    post_reboot_delay: "{{ reboot_check }}"
    msg: "{{ reboot_message }}"
  async: 1
  poll: 0
  ignore_errors: yes
  register: reboot_result
  notify:
    - gather facts
    - print result
  when:
    - reboot_always | bool
      or (reboot_required_stat is defined and reboot_required_stat.stat.exists)
      or (needs_restarting_stat is defined and needs_restarting_stat.stat.exists and needsrestarting.rc == 1)
      or (freebsd_version is defined and freebsd_version.changed)
  tags: reboot
