---
# handlers file for reboot


- name: gather facts
  setup:


- name: print uptime
  debug:
    msg: "Uptime: {{ ansible_uptime_seconds }} sec."
  when: ansible_distribution != 'FreeBSD'
  listen: gather facts


- name: debug freebsd python
  debug:
    msg:
      - "{{ freebsd_python_install }}"


- name: debug freebsd
  debug:
    msg:
      - New kernel - {{ freebsd_version.stdout }}
      - Active kernel - {{ ansible_kernel }}
      - Changed - {{ freebsd_version.changed }}


- name: print result
  debug:
    msg: "{{ lookup('template', 'result.j2') }}"

